export interface Recipe {
  id: number;
  name: string;
  calories: number;
  prepTime: number;
  cookTime: number;
  servings: number;
  image: string;
  cyclePhase?: 'menstrual' | 'follicular' | 'ovulation' | 'luteal';
  ingredients: { item: string; amount: string }[];
  instructions: string[];
  nutrition: {
    protein: number;
    carbs: number;
    fat: number;
    fiber: number;
  };
}

export const mockRecipes: Recipe[] = [
  {
    id: 1,
    name: 'Quinoa Buddha Bowl',
    calories: 420,
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
    cyclePhase: 'follicular',
    ingredients: [
      { item: 'Quinoa', amount: '1 cup' },
      { item: 'Chickpeas', amount: '1 can (15 oz)' },
      { item: 'Kale', amount: '2 cups chopped' },
      { item: 'Sweet potato', amount: '1 medium, cubed' },
      { item: 'Avocado', amount: '1, sliced' },
      { item: 'Tahini dressing', amount: '3 tbsp' },
      { item: 'Olive oil', amount: '2 tbsp' },
      { item: 'Lemon juice', amount: '1 tbsp' },
    ],
    instructions: [
      'Cook quinoa according to package instructions',
      'Roast sweet potato cubes at 400°F for 25 minutes',
      'Drain and rinse chickpeas, then roast for 15 minutes',
      'Massage kale with olive oil and lemon juice',
      'Assemble bowls with quinoa as base',
      'Top with roasted vegetables, chickpeas, and avocado',
      'Drizzle with tahini dressing and serve',
    ],
    nutrition: {
      protein: 18,
      carbs: 52,
      fat: 16,
      fiber: 12,
    },
  },
  {
    id: 2,
    name: 'Grilled Salmon with Asparagus',
    calories: 385,
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
    cyclePhase: 'ovulation',
    ingredients: [
      { item: 'Salmon fillets', amount: '2 (6 oz each)' },
      { item: 'Asparagus', amount: '1 bunch' },
      { item: 'Garlic', amount: '3 cloves, minced' },
      { item: 'Lemon', amount: '1, sliced' },
      { item: 'Olive oil', amount: '2 tbsp' },
      { item: 'Fresh dill', amount: '2 tbsp' },
      { item: 'Salt and pepper', amount: 'to taste' },
    ],
    instructions: [
      'Preheat grill or oven to 400°F',
      'Season salmon with salt, pepper, and dill',
      'Toss asparagus with olive oil and garlic',
      'Place salmon skin-side down on grill',
      'Add asparagus to grill alongside salmon',
      'Cook for 12-15 minutes until salmon flakes easily',
      'Serve with lemon slices',
    ],
    nutrition: {
      protein: 34,
      carbs: 8,
      fat: 22,
      fiber: 3,
    },
  },
  {
    id: 3,
    name: 'Chickpea Curry',
    calories: 365,
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800',
    cyclePhase: 'luteal',
    ingredients: [
      { item: 'Chickpeas', amount: '2 cans (15 oz each)' },
      { item: 'Coconut milk', amount: '1 can (14 oz)' },
      { item: 'Onion', amount: '1 large, diced' },
      { item: 'Tomatoes', amount: '2 cups diced' },
      { item: 'Curry powder', amount: '2 tbsp' },
      { item: 'Ginger', amount: '1 tbsp minced' },
      { item: 'Garlic', amount: '4 cloves, minced' },
      { item: 'Spinach', amount: '2 cups' },
    ],
    instructions: [
      'Sauté onion in oil until translucent',
      'Add garlic and ginger, cook for 1 minute',
      'Stir in curry powder and cook until fragrant',
      'Add tomatoes and cook for 5 minutes',
      'Pour in coconut milk and chickpeas',
      'Simmer for 15 minutes',
      'Stir in spinach until wilted',
      'Serve over rice or with naan bread',
    ],
    nutrition: {
      protein: 14,
      carbs: 48,
      fat: 12,
      fiber: 10,
    },
  },
  {
    id: 4,
    name: 'Mediterranean Pasta',
    calories: 445,
    prepTime: 10,
    cookTime: 15,
    servings: 3,
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
    cyclePhase: 'follicular',
    ingredients: [
      { item: 'Whole wheat pasta', amount: '12 oz' },
      { item: 'Cherry tomatoes', amount: '2 cups halved' },
      { item: 'Olives', amount: '1/2 cup sliced' },
      { item: 'Feta cheese', amount: '1/2 cup crumbled' },
      { item: 'Spinach', amount: '3 cups' },
      { item: 'Olive oil', amount: '3 tbsp' },
      { item: 'Garlic', amount: '4 cloves, minced' },
      { item: 'Fresh basil', amount: '1/4 cup' },
    ],
    instructions: [
      'Cook pasta according to package directions',
      'In a large pan, heat olive oil',
      'Sauté garlic until fragrant',
      'Add cherry tomatoes and cook until softened',
      'Add spinach and cook until wilted',
      'Drain pasta and add to pan',
      'Toss with olives, feta, and fresh basil',
      'Season with salt and pepper to taste',
    ],
    nutrition: {
      protein: 16,
      carbs: 58,
      fat: 18,
      fiber: 8,
    },
  },
  {
    id: 5,
    name: 'Teriyaki Chicken Stir-Fry',
    calories: 410,
    prepTime: 15,
    cookTime: 12,
    servings: 3,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800',
    cyclePhase: 'ovulation',
    ingredients: [
      { item: 'Chicken breast', amount: '1 lb, sliced' },
      { item: 'Broccoli', amount: '2 cups florets' },
      { item: 'Bell peppers', amount: '2, sliced' },
      { item: 'Teriyaki sauce', amount: '1/3 cup' },
      { item: 'Ginger', amount: '1 tbsp minced' },
      { item: 'Garlic', amount: '3 cloves, minced' },
      { item: 'Sesame oil', amount: '1 tbsp' },
      { item: 'Brown rice', amount: '2 cups cooked' },
    ],
    instructions: [
      'Heat sesame oil in a wok or large pan',
      'Add chicken and cook until golden',
      'Remove chicken and set aside',
      'Add garlic and ginger, stir for 30 seconds',
      'Add broccoli and peppers, stir-fry for 4 minutes',
      'Return chicken to pan',
      'Pour teriyaki sauce and toss to coat',
      'Serve over brown rice',
    ],
    nutrition: {
      protein: 32,
      carbs: 42,
      fat: 10,
      fiber: 5,
    },
  },
  {
    id: 6,
    name: 'Greek Salad with Grilled Chicken',
    calories: 340,
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
    cyclePhase: 'ovulation',
    ingredients: [
      { item: 'Chicken breast', amount: '8 oz' },
      { item: 'Romaine lettuce', amount: '4 cups chopped' },
      { item: 'Cucumber', amount: '1 large, diced' },
      { item: 'Cherry tomatoes', amount: '1 cup halved' },
      { item: 'Red onion', amount: '1/4 cup sliced' },
      { item: 'Kalamata olives', amount: '1/4 cup' },
      { item: 'Feta cheese', amount: '1/3 cup crumbled' },
      { item: 'Greek dressing', amount: '3 tbsp' },
    ],
    instructions: [
      'Season chicken with oregano, salt, and pepper',
      'Grill chicken for 5 minutes per side',
      'Let chicken rest, then slice',
      'Combine lettuce, cucumber, tomatoes, and onion',
      'Top with olives and feta cheese',
      'Add sliced chicken',
      'Drizzle with Greek dressing and toss',
    ],
    nutrition: {
      protein: 28,
      carbs: 14,
      fat: 18,
      fiber: 4,
    },
  },
  {
    id: 7,
    name: 'Sweet Potato & Black Bean Tacos',
    calories: 380,
    prepTime: 10,
    cookTime: 20,
    servings: 3,
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800',
    cyclePhase: 'luteal',
    ingredients: [
      { item: 'Sweet potatoes', amount: '2 medium, cubed' },
      { item: 'Black beans', amount: '1 can (15 oz)' },
      { item: 'Corn tortillas', amount: '6' },
      { item: 'Avocado', amount: '1, sliced' },
      { item: 'Red cabbage', amount: '1 cup shredded' },
      { item: 'Lime', amount: '2, juiced' },
      { item: 'Cumin', amount: '1 tsp' },
      { item: 'Cilantro', amount: '1/4 cup chopped' },
    ],
    instructions: [
      'Toss sweet potato cubes with cumin and oil',
      'Roast at 425°F for 20 minutes',
      'Warm black beans in a pan',
      'Heat tortillas in a dry skillet',
      'Assemble tacos with sweet potatoes and beans',
      'Top with cabbage, avocado, and cilantro',
      'Squeeze lime juice over tacos',
      'Serve immediately',
    ],
    nutrition: {
      protein: 12,
      carbs: 62,
      fat: 10,
      fiber: 14,
    },
  },
  {
    id: 8,
    name: 'Avocado Toast with Poached Eggs',
    calories: 320,
    prepTime: 5,
    cookTime: 5,
    servings: 1,
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800',
    cyclePhase: 'menstrual',
    ingredients: [
      { item: 'Whole grain bread', amount: '2 slices' },
      { item: 'Avocado', amount: '1 ripe' },
      { item: 'Eggs', amount: '2' },
      { item: 'Cherry tomatoes', amount: '1/2 cup halved' },
      { item: 'Lemon juice', amount: '1 tsp' },
      { item: 'Red pepper flakes', amount: 'pinch' },
      { item: 'Salt and pepper', amount: 'to taste' },
    ],
    instructions: [
      'Toast bread until golden',
      'Mash avocado with lemon juice, salt, and pepper',
      'Bring water to gentle simmer for poaching',
      'Crack eggs into water and poach for 3-4 minutes',
      'Spread avocado on toast',
      'Top with poached eggs',
      'Add cherry tomatoes and red pepper flakes',
    ],
    nutrition: {
      protein: 18,
      carbs: 32,
      fat: 16,
      fiber: 10,
    },
  },
  {
    id: 9,
    name: 'Berry Protein Smoothie Bowl',
    calories: 285,
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800',
    cyclePhase: 'follicular',
    ingredients: [
      { item: 'Frozen mixed berries', amount: '1 cup' },
      { item: 'Banana', amount: '1 frozen' },
      { item: 'Protein powder', amount: '1 scoop' },
      { item: 'Almond milk', amount: '1/2 cup' },
      { item: 'Granola', amount: '1/4 cup' },
      { item: 'Chia seeds', amount: '1 tbsp' },
      { item: 'Fresh berries', amount: 'for topping' },
    ],
    instructions: [
      'Blend frozen berries, banana, protein powder, and almond milk',
      'Blend until thick and creamy',
      'Pour into a bowl',
      'Top with granola, chia seeds, and fresh berries',
      'Serve immediately',
    ],
    nutrition: {
      protein: 22,
      carbs: 42,
      fat: 6,
      fiber: 8,
    },
  },
  {
    id: 10,
    name: 'Veggie Omelet',
    calories: 295,
    prepTime: 5,
    cookTime: 8,
    servings: 1,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800',
    cyclePhase: 'menstrual',
    ingredients: [
      { item: 'Eggs', amount: '3 large' },
      { item: 'Spinach', amount: '1 cup' },
      { item: 'Mushrooms', amount: '1/2 cup sliced' },
      { item: 'Bell pepper', amount: '1/4 cup diced' },
      { item: 'Onion', amount: '2 tbsp diced' },
      { item: 'Cheese', amount: '2 tbsp shredded' },
      { item: 'Olive oil', amount: '1 tsp' },
    ],
    instructions: [
      'Whisk eggs with salt and pepper',
      'Sauté vegetables in olive oil until tender',
      'Pour eggs over vegetables',
      'Cook until edges set',
      'Add cheese to one half',
      'Fold omelet and cook until done',
      'Serve hot',
    ],
    nutrition: {
      protein: 24,
      carbs: 8,
      fat: 18,
      fiber: 2,
    },
  },
];